### ISSUE TITLE
Consider allowing GPL style open source license

### ISSUE THREAD

**Issue by kevinoriordan** [gilt/standards#39]
Permissive licenses such as APL and MIT make the most sense for libraries as we want people to be able to link to our libraries at will without being forced to adopt the library's license in their own application.

However, some people may prefer that if Gilt open sources a fully self contained application and someone makes enhancements to that application, that Gilt has access to those enhancements. For this case, licenses such as GPL and EPL may be more suitable as they require modified versions of the application to also carry the GPL or EPL license. People may object on philosophical grounds but I wanted to open it up for discussion.

**Comment by zcohn** [comment]
We are closing this issue based on discussion with the impacted team. The consensus was that the current approach--promoting more permissive licenses--is likely to lead to better outcomes even in terms of promoting contributions.
